Write explanation for why we combined sprint 2 and 3
chhoumann/p5 pull request #21
Opened 2021-11-09 11:02 UTC by chhoumann

2021-11-10 08:55 UTC, RasmusHoeyerHansen requested changes

2021-11-10 08:55 UTC, RasmusHoeyerHansen commented on sections/Chapter 5 Sprint 3/Sprint3.tex
> +We have chosen to combine our descriptions of the two previous sprints into one sprint. Sprint 2 was supposed to be the sprint where the search engine was fixed, but ended up being swallowed by plann
Maybe "swallowed by planning and collaboration efforts between the groups knox."

Kunne være rart at vide hvor langt sprint 3 så egentlig var.

2021-11-11 08:56 UTC, chhoumann reviewed
GJ

2021-11-11 08:56 UTC, chhoumann commented on sections/Chapter 5 Sprint 3/Sprint3.tex
> +All in all the sprint lasted from 21st of September to 4th of October.
Comma

2021-11-11 08:56 UTC, chhoumann commented on sections/Chapter 5 Sprint 3/Sprint3.tex
> +All in all the sprint lasted from 21st of September to 4th of October.
```suggestion
All in all the, sprint lasted from 21st of September to 4th of October. 
```

2021-11-11 08:56 UTC, merged