PostgreSQL and relational databases
chhoumann/p5 pull request #24
Opened 2021-11-09 13:11 UTC by Pattrigue

2021-11-10 08:48 UTC, RasmusHoeyerHansen requested changes
I would like a clearer separation between the mathematics of relational databases. I would also like a separation between a database design (Entity models) and SQL. 
One could consider writing something 'rød tråd' ala:
Postgres is implemented last year --> that is a relational database --> relational databases can be described using relations of tuples --> the tuples follow attributes of the relation --> to ensure unique tuples, keys are used --> In a relational database, the relations are represented in tables, with columns describing the attributes, and with each row representing a tuple of information --> to ensure good database design (minimal storage, maximum information) one can design the relations and map them to EM and implement them in database --> DDL --> DML --> transactions.
The short mention of the layers of the database is okay. It might also be worth mentioning that designing for storage and designing to represent the domain can be mutually exclusive.

2021-11-10 08:48 UTC, RasmusHoeyerHansen commented on sections/Chapter 3 Sprint 1/postgreSQL.tex
> +The group last year chose to implement the database using PostgreSQL which is an relational database system \cite{knox2020}.
The database? Which one? All of them?

2021-11-10 08:48 UTC, RasmusHoeyerHansen commented on sections/Chapter 3 Sprint 1/postgreSQL.tex
> +A relational database is a collection of tables, known as relations. Relational databases are used to provide access to related data points.
I miss a mathematical describtion of relations. Something ala "A relational database can be described mathematically as a collection of relations containing tuples. Each relation contains attributes describing the domain of the values of the tuples. A relational database describes these relations in the form of a table with columns corresponding to the name and domain of the attributes of the represented relation attributes. The rows of the table correspond to tuple values of the relation.
In the context of an enterprise......"

2021-11-10 08:48 UTC, RasmusHoeyerHansen commented on sections/Chapter 3 Sprint 1/postgreSQL.tex
> +The goal of the designing such relations is to represent entities as intuitively as possible, making it easy to establish relationships between them.
Is that the only goal of designing relations? It also breaks a bit away from the description of relational databases as mathematical concepts - then its immediately returned to with a description of keys.

2021-11-10 08:48 UTC, RasmusHoeyerHansen commented on sections/Chapter 3 Sprint 1/postgreSQL.tex
> +Executing a query instructs the database system to perform a set of operations to compute a desired result, known as transactions.
Not all queries are transactions.

2021-11-11 08:26 UTC, Ivikhostrup approved these changes

2021-11-11 08:27 UTC, RasmusHoeyerHansen approved these changes

2021-11-11 08:27 UTC, merged