Reorganization of sprint 3
chhoumann/p5 pull request #46
Opened 2021-11-30 12:42 UTC by Ivikhostrup

Review guide:

* Is the intro satisfying? Does it pick up on the second sprint properly?
* Is the review/retro satisfying?
* Does the remainder of the third sprint need some updates in terms of head/tail?

2021-11-30 14:18 UTC, MrHonket commented on sections/Chapter 5 Sprint 3/retrospective.tex
>      \item Sprints changed to 2-week duration. 4 weeks is too long.\todo{We might not be allowed to change the duration of sprints.}
```suggestion
    \item Sprints changed to 2-week duration. 4 weeks is too long.
```

2021-11-30 14:27 UTC, MrHonket reviewed
Overall I feel like the reorganization makes sense.
However I feel like the leftover todo's in the retrospective should be fixed before merging.

2021-12-07 12:13 UTC, MrHonket requested changes

2021-12-07 12:13 UTC, MrHonket commented on sections/Chapter 5 Sprint 3/docker_implementation.tex
> +The final major goal of this sprint was to achieve the encapsulation that we described in the second sprint. In order to achieve this we had to add both the API and database to a container each and c
Perhaps add a ref to the part where the wanted encapsulation is described?

2021-12-07 12:13 UTC, MrHonket commented on sections/Chapter 5 Sprint 3/retrospective.tex
>  Tasks should also not be marked as complete before they have been shipped to production, as per Scrum convention---a task is not done before it is delivered\todo{Include source - Scrum book by Jeff S
Include the source requested

2021-12-07 12:24 UTC, Ivikhostrup commented on sections/Chapter 5 Sprint 3/CRUD.tex
> +This Schema consists of two \texttt{GET} methods and a single \texttt{POST} method.
```suggestion
This schema consists of two \texttt{GET} methods and a single \texttt{POST} method.
```

2021-12-07 12:25 UTC, mkju19 approved these changes

2021-12-07 12:26 UTC, MrHonket approved these changes

2021-12-07 12:28 UTC, merged